site_name: API
repo_url: https://github.com/Ostrock/api
repo_name: Ostrock/API 
edit_uri: tree/main/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [api]

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css 