from datetime import datetime as dt

import pytest


@pytest.fixture
def fake_utcnow():
    return dt(2023, 2, 11, 15, 28, 3, 576205)


@pytest.fixture
def correct_google_geocode():
    values = [
        {
            'address_components': [
                {
                    'long_name': '13207-780',
                    'short_name': '13207-780',
                    'types': ['postal_code'],
                },
                {
                    'long_name': 'Rua Bela Vista',
                    'short_name': 'R. Bela Vista',
                    'types': ['route'],
                },
                {
                    'long_name': 'Bela Vista',
                    'short_name': 'Bela Vista',
                    'types': [
                        'political',
                        'sublocality',
                        'sublocality_level_1',
                    ],
                },
                {
                    'long_name': 'Jundiaí',
                    'short_name': 'Jundiaí',
                    'types': ['administrative_area_level_2', 'political'],
                },
                {
                    'long_name': 'São Paulo',
                    'short_name': 'SP',
                    'types': ['administrative_area_level_1', 'political'],
                },
                {
                    'long_name': 'Brazil',
                    'short_name': 'BR',
                    'types': ['country', 'political'],
                },
            ],
            'formatted_address': 'R. Bela Vista - Bela Vista, Jundiaí - SP, 13207-780, Brazil',
            'geometry': {
                'bounds': {
                    'northeast': {'lat': -23.1901048, 'lng': -46.8870748},
                    'southwest': {'lat': -23.1988781, 'lng': -46.8894996},
                },
                'location': {'lat': -23.19351, 'lng': -46.8877366},
                'location_type': 'APPROXIMATE',
                'viewport': {
                    'northeast': {
                        'lat': -23.1901048,
                        'lng': -46.8869382197085,
                    },
                    'southwest': {
                        'lat': -23.1988781,
                        'lng': -46.8896361802915,
                    },
                },
            },
            'place_id': 'ChIJzzHyoJYmz5QRIiEjplWVLwY',
            'postcode_localities': [
                'Bela Vista',
                'Centro',
                'Vila Boaventura',
                'Vila Pirapora',
                'Vila Virginia',
            ],
            'types': ['postal_code'],
        }
    ]


@pytest.fixture
def correct_result_with_more_than_one():
    values = [
        {
            'address_components': [
                {
                    'long_name': '13207-780',
                    'short_name': '13207-780',
                    'types': ['postal_code'],
                },
                {
                    'long_name': 'Rua Bela Vista',
                    'short_name': 'R. Bela Vista',
                    'types': ['route'],
                },
                {
                    'long_name': 'Bela Vista',
                    'short_name': 'Bela Vista',
                    'types': [
                        'political',
                        'sublocality',
                        'sublocality_level_1',
                    ],
                },
                {
                    'long_name': 'Jundiaí',
                    'short_name': 'Jundiaí',
                    'types': ['administrative_area_level_2', 'political'],
                },
                {
                    'long_name': 'São Paulo',
                    'short_name': 'SP',
                    'types': ['administrative_area_level_1', 'political'],
                },
                {
                    'long_name': 'Brazil',
                    'short_name': 'BR',
                    'types': ['country', 'political'],
                },
            ],
            'formatted_address': 'R. Bela Vista - Bela Vista, Jundiaí - SP, 13207-780, Brazil',
            'geometry': {
                'bounds': {
                    'northeast': {'lat': -23.1901048, 'lng': -46.8870748},
                    'southwest': {'lat': -23.1988781, 'lng': -46.8894996},
                },
                'location': {'lat': -23.19351, 'lng': -46.8877366},
                'location_type': 'APPROXIMATE',
                'viewport': {
                    'northeast': {
                        'lat': -23.1901048,
                        'lng': -46.8869382197085,
                    },
                    'southwest': {
                        'lat': -23.1988781,
                        'lng': -46.8896361802915,
                    },
                },
            },
            'place_id': 'ChIJzzHyoJYmz5QRIiEjplWVLwY',
            'postcode_localities': [
                'Bela Vista',
                'Centro',
                'Vila Boaventura',
                'Vila Pirapora',
                'Vila Virginia',
            ],
            'types': ['postal_code'],
        },
        {
            'address_components': [
                {
                    'long_name': '1705 ED',
                    'short_name': '1705 ED',
                    'types': ['postal_code'],
                },
                {
                    'long_name': 'Heerhugowaard',
                    'short_name': 'Heerhugowaard',
                    'types': ['locality', 'political'],
                },
                {
                    'long_name': 'Heerhugowaard',
                    'short_name': 'Heerhugowaard',
                    'types': ['administrative_area_level_2', 'political'],
                },
                {
                    'long_name': 'North Holland',
                    'short_name': 'NH',
                    'types': ['administrative_area_level_1', 'political'],
                },
                {
                    'long_name': 'Netherlands',
                    'short_name': 'NL',
                    'types': ['country', 'political'],
                },
            ],
            'formatted_address': '1705 ED Heerhugowaard, Netherlands',
            'geometry': {
                'bounds': {
                    'northeast': {'lat': 52.6513691, 'lng': 4.8329682},
                    'southwest': {'lat': 52.6499037, 'lng': 4.8294103},
                },
                'location': {'lat': 52.6507478, 'lng': 4.8314845},
                'location_type': 'APPROXIMATE',
                'viewport': {
                    'northeast': {'lat': 52.65198538029149, 'lng': 4.8329682},
                    'southwest': {'lat': 52.64928741970849, 'lng': 4.8294103},
                },
            },
            'place_id': 'ChIJMeIndzRUz0cRcb09ZzmnIlg',
            'types': ['postal_code'],
        },
    ]

    return values


@pytest.fixture
def fake_dataseries():
    values = [
        {
            'timepoint': 3,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 21,
            'rh2m': '24%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 6,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 23,
            'rh2m': '23%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 9,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 21,
            'rh2m': '23%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 12,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '33%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 15,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 15,
            'rh2m': '37%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 18,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 14,
            'rh2m': '40%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 21,
            'cloudcover': 7,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 13,
            'rh2m': '42%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'mcloudynight',
        },
        {
            'timepoint': 24,
            'cloudcover': 5,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '30%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'pcloudyday',
        },
        {
            'timepoint': 27,
            'cloudcover': 4,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 24,
            'rh2m': '22%',
            'wind10m': {'direction': 'S', 'speed': 4},
            'weather': 'pcloudyday',
        },
        {
            'timepoint': 30,
            'cloudcover': 6,
            'lifted_index': 6,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 27,
            'rh2m': '15%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'mcloudyday',
        },
        {
            'timepoint': 33,
            'cloudcover': 4,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 24,
            'rh2m': '18%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 36,
            'cloudcover': 7,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 22,
            'rh2m': '22%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'mcloudynight',
        },
        {
            'timepoint': 39,
            'cloudcover': 9,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 20,
            'rh2m': '20%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'cloudynight',
        },
        {
            'timepoint': 42,
            'cloudcover': 8,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '22%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'cloudynight',
        },
        {
            'timepoint': 45,
            'cloudcover': 9,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 16,
            'rh2m': '28%',
            'wind10m': {'direction': 'S', 'speed': 2},
            'weather': 'cloudynight',
        },
        {
            'timepoint': 48,
            'cloudcover': 9,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 20,
            'rh2m': '20%',
            'wind10m': {'direction': 'NE', 'speed': 2},
            'weather': 'cloudyday',
        },
        {
            'timepoint': 51,
            'cloudcover': 2,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 26,
            'rh2m': '13%',
            'wind10m': {'direction': 'SE', 'speed': 2},
            'weather': 'clearday',
        },
        {
            'timepoint': 54,
            'cloudcover': 1,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 29,
            'rh2m': '10%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 57,
            'cloudcover': 1,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 25,
            'rh2m': '12%',
            'wind10m': {'direction': 'E', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 60,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 22,
            'rh2m': '24%',
            'wind10m': {'direction': 'E', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 63,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '30%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 66,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 14,
            'rh2m': '48%',
            'wind10m': {'direction': 'N', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 69,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 13,
            'rh2m': '66%',
            'wind10m': {'direction': 'N', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 72,
            'cloudcover': 1,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 16,
            'rh2m': '45%',
            'wind10m': {'direction': 'E', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 75,
            'cloudcover': 1,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 26,
            'rh2m': '16%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 78,
            'cloudcover': 1,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 30,
            'rh2m': '8%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 81,
            'cloudcover': 1,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 27,
            'rh2m': '10%',
            'wind10m': {'direction': 'SE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 84,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 24,
            'rh2m': '11%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 87,
            'cloudcover': 3,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 21,
            'rh2m': '11%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 90,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 20,
            'rh2m': '19%',
            'wind10m': {'direction': 'W', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 93,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 21,
            'rh2m': '12%',
            'wind10m': {'direction': 'S', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 96,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 24,
            'rh2m': '10%',
            'wind10m': {'direction': 'NW', 'speed': 3},
            'weather': 'pcloudyday',
        },
        {
            'timepoint': 99,
            'cloudcover': 2,
            'lifted_index': 6,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 28,
            'rh2m': '22%',
            'wind10m': {'direction': 'NW', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 102,
            'cloudcover': 5,
            'lifted_index': 6,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 29,
            'rh2m': '20%',
            'wind10m': {'direction': 'NW', 'speed': 3},
            'weather': 'pcloudyday',
        },
        {
            'timepoint': 105,
            'cloudcover': 7,
            'lifted_index': 6,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 26,
            'rh2m': '28%',
            'wind10m': {'direction': 'N', 'speed': 3},
            'weather': 'mcloudynight',
        },
        {
            'timepoint': 108,
            'cloudcover': 6,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 23,
            'rh2m': '30%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'mcloudynight',
        },
        {
            'timepoint': 111,
            'cloudcover': 6,
            'lifted_index': 10,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 18,
            'rh2m': '35%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'mcloudynight',
        },
        {
            'timepoint': 114,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 15,
            'rh2m': '55%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 117,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 13,
            'rh2m': '70%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 120,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 14,
            'rh2m': '57%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 123,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 20,
            'rh2m': '35%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 126,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 23,
            'rh2m': '27%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 129,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 21,
            'rh2m': '34%',
            'wind10m': {'direction': 'E', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 132,
            'cloudcover': 3,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '35%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 135,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 15,
            'rh2m': '50%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 138,
            'cloudcover': 5,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 12,
            'rh2m': '46%',
            'wind10m': {'direction': 'N', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 141,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 11,
            'rh2m': '40%',
            'wind10m': {'direction': 'N', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 144,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 13,
            'rh2m': '32%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 147,
            'cloudcover': 3,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 18,
            'rh2m': '22%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudyday',
        },
        {
            'timepoint': 150,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 22,
            'rh2m': '22%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudyday',
        },
        {
            'timepoint': 153,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 18,
            'rh2m': '21%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 156,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 16,
            'rh2m': '31%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 159,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 13,
            'rh2m': '35%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 162,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 11,
            'rh2m': '42%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 165,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 10,
            'rh2m': '36%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 168,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 13,
            'rh2m': '26%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 171,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '25%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 174,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 20,
            'rh2m': '21%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearday',
        },
        {
            'timepoint': 177,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 17,
            'rh2m': '23%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudynight',
        },
        {
            'timepoint': 180,
            'cloudcover': 6,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 14,
            'rh2m': '31%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'mcloudynight',
        },
        {
            'timepoint': 183,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 12,
            'rh2m': '35%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 186,
            'cloudcover': 1,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 10,
            'rh2m': '35%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 189,
            'cloudcover': 2,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 9,
            'rh2m': '36%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'clearnight',
        },
        {
            'timepoint': 192,
            'cloudcover': 4,
            'lifted_index': 15,
            'prec_type': 'none',
            'prec_amount': 0,
            'temp2m': 12,
            'rh2m': '27%',
            'wind10m': {'direction': 'NE', 'speed': 3},
            'weather': 'pcloudyday',
        },
    ]
    return values
